#!/bin/bash

DEBUG_FLAG="-DDEBUG_MODE=FALSE"
MUSIC_FLAG="-DNO_MUSIC=FALSE"

for var in "$@"; do
    if [[ "$var" == "--debug" ]]; then
        DEBUG_FLAG="-DDEBUG_MODE=TRUE"
    fi
    if [[ "$var" == "--no-music" ]]; then
        MUSIC_FLAG="-DNO_MUSIC=TRUE"
    fi
done

mkdir build; cd build; cmake $DEBUG_FLAG $MUSIC_FLAG .. && make;
